### ISSUE TITLE
Multiple cursors for `findText`

### ISSUE THREAD

**Issue by anthonyjclark** [DCsunset/vscode-modal-editor#3] opened 2022-09-08 03:11 UTC
(Thanks for the extension, I am really enjoying it so far!)

Do you have plans to make [`findText`](https://github.com/DCsunset/vscode-modal-editor/blob/baae0388d976b177a952c1e3d653018d27069fa5/src/commands.ts#L263) work with multiple cursors?

For example, the following keymap will only jump forward for the primary cursor. The other cursors vanish.

```js
		// Jump till next typed character
		"t": {
			"": recordMotion(repeatable([
				"cancelSelection",
				{
					command: "modalEditor.findText",
					computedArgs: true,
					args: `{
						text: _ctx.keys.charAt(_ctx.keys.length-1),
						till: true,
						select: false
					}`
				}
			]))
		},
```

If you can give some pointers, I could attempt the change and submit a PR.

**Comment by DCsunset** [comment] 2022-09-12 00:29
Hello,

The reason why other cursors vanish is that currently `findText` changes only the main selection. To fix it, all the selections should be processed in the same way.
You can attempt the change if you are keen on it. If not, I think I can fix it by the end of next week.

**Comment by anthonyjclark** [comment] 2022-09-12 02:48
I'll let you handle it :) but I am happy to contribute if you get bogged down.

On a related note, I noticed that my "move next word start" (and backward) mapping has an odd behavior. It works for all cursors on the first attempt, but then on the second press it too kills the secondary cursors. I am using your example from helix.js, but I turned it into a function. You can see my entire mapping file here if it is useful [helixish.js](https://gist.github.com/anthonyjclark/1de4882c13ffd3c61863bc657557253e).



https://user-images.githubusercontent.com/4173647/189564976-8eaef349-6f5e-4589-bb2a-c4113865abdc.mov

**Comment by DCsunset** [comment] 2022-09-13 02:59
Maybe these two issues are related but I'm not sure now. I'll take a closer look at it after I fix the first problem.

**Comment by DCsunset** [comment] 2022-09-14 20:51
Hi, I think I've fixed `findText` in the latest commits. Besides, the second issue you mentioned seems to be caused by `cancelSelection` command, which kills all the secondary cursors if there's any non-empty selection.

So I've added another command called `modalEditor.clearSelections` that can clear selections but keep all cursors. You can replace the original command with it and it should fix the second issue.

If you have some time, would you mind trying the latest unpublished version? You may need to clone the repo and package it locally.

**Comment by anthonyjclark** [comment] 2022-09-14 22:08
> 

That sounds great! I should have some time in the next day or two to give it a try.

**Comment by anthonyjclark** [comment] 2022-09-15 04:09
I have not thoroughly tested, but everything seems to work aside from one thing: *I lose secondary cursors when in selection mode and moving backwards.*

This does not happen with moving forward (jumping, moving by word, and moving by character all seem to work).

I also tried using the built-in keybindings (multiple cursors at the end of multiple lines; press shift+option+left), and they seem to work fine. For reference, my back-one-word key is just:

```javascript
"b": repeatable("cursorWordStartLeftSelect"),
```

I am not sure why this would result in the behavior I described.

**Comment by DCsunset** [comment] 2022-09-17 16:02
Thanks for your feedback. The reason is that the inclusive selection was not implemented correctly for multiple cursors. I've fixed it in the latest commit.

It would be great if you could verify that it works for you as well.

**Comment by anthonyjclark** [comment] 2022-09-17 17:17
I didn't thoroughly test, but everything I tried is working.

Thanks again.

**Comment by DCsunset** [comment] 2022-09-17 20:30
Great! I'll publish a new version and close this issue later.

**Closed** 2022-09-17 22:48 UTC
Labels: bug
